Repository CSG6Project1/cambodia_geography_mobile, pull requests merged in 2021-08, with the labels that each got.

#58 close #57 fix search history list
  lib/screens/search/cg_search_delegate.dart
  pubspec.lock
Labels: enhancement

#60 Add circle splash screen
  lib/main.dart
Labels: XS, design, feature

#62 54 comment on place
  lib/models/apis/base_list_model.dart
  lib/screens/comment/comment_screen.dart
  lib/screens/places/places_screen.dart
  lib/services/apis/base_api.dart
  lib/services/apis/comment/create_commen_api.dart
Labels: feature

#63 udpate add new comment
  lib/main.dart
  lib/screens/comment/comment_screen.dart
Labels: enhancement, design, feature

#66 65 add user detail api
  lib/app.dart
  lib/models/apis/object_name_url_model.dart
  lib/screens/drawer/app_drawer.dart
  lib/screens/drawer/local_widgets/diagonal_path_clipper.dart
  lib/services/apis/base_api.dart
  lib/services/apis/users/user_api.dart
Labels: feature

#71 close #70 user screen design
  .firebase/hosting.YnVpbGQvd2Vi.cache
  lib/screens/auth/login_screen.dart
  lib/screens/user/user_screen.dart
  lib/services/images/image_picker_service.dart
  lib/widgets/cg_network_image_loader.dart
Labels: design, XS

#73 close #72 update user info api
  lib/configs/route_config.dart
  lib/models/user/user_model.dart
  lib/screens/admin/edit_place_screen.dart
  lib/screens/drawer/app_drawer.dart
  lib/screens/user/user_screen.dart
  lib/services/apis/base_api.dart
  lib/services/apis/users/user_api.dart
Labels: feature

#75 close #74 bookmark screen design
  lib/app.dart
  lib/models/user/user_model.dart
  lib/provider_scope.dart
  lib/providers/bookmark_editing_provider.dart
  lib/screens/drawer/app_drawer.dart
  lib/screens/places/local_widgets/place_card.dart
  lib/screens/user/bookmark_screen.dart
  lib/screens/user/user_screen.dart
  lib/widgets/cg_dropdown_field.dart
Labels: design

#78 close #77 autocomplete API
  lib/models/search/autocompleter_list_model.dart
  lib/models/search/autocompleter_model.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/local_widgets/search_button.dart
  lib/screens/search/cg_search_delegate.dart
  lib/services/apis/search/search_autocomplete_api.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#80 close #79 improve text field & auth keyboard action
  lib/exports/widgets_exports.dart
  lib/screens/auth/login_screen.dart
  lib/screens/auth/signup_screen.dart
  lib/screens/map/map_screen.dart
  lib/widgets/text_fields/cg_email_field.dart
  lib/widgets/text_fields/cg_password_field.dart
  lib/widgets/text_fields/cg_text_field.dart
Labels: enhancement

#81 close #76 province detail screen
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/exports/widgets_exports.dart
  lib/helpers/app_helper.dart
  lib/screens/place_detail/local_widgets/place_title.dart
  lib/screens/place_detail/place_detail_screen.dart
  lib/screens/province/province_detail_screen.dart
  lib/widgets/cg_image_appbar.dart
Labels: design

#83 close #82 update search history deletion
  lib/screens/search/cg_search_delegate.dart
Labels: design

#86 84 social authentication
  lib/app_builder.dart
  lib/screens/auth/local_widgets/social_buttons.dart
  lib/screens/auth/login_screen.dart
  lib/screens/auth/signup_screen.dart
  lib/screens/drawer/app_drawer.dart
  lib/screens/home/home_screen.dart
  lib/screens/search/cg_search_delegate.dart
  lib/services/apis/users/user_register_api.dart
  lib/services/authentications/auth_api.dart
Labels: feature, S

#92 close #90 email confirmation flow
  ios/Runner/Info.plist
  lib/app.dart
  lib/configs/route_config.dart
  lib/models/user/confirmation_model.dart
  lib/models/user/user_model.dart
  lib/screens/auth/confirmation_screen.dart
  lib/screens/auth/login_screen.dart
  lib/screens/auth/signup_screen.dart
  lib/services/apis/base_api.dart
  lib/services/apis/users/confirmation_api.dart
  lib/services/apis/users/user_api.dart
  pubspec.lock
  pubspec.yaml
Labels: design, feature

#94 close #93 pause timer on app inactive
  lib/app.dart
  lib/screens/auth/confirmation_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#95 80 update comment
  ios/Podfile.lock
  lib/screens/comment/comment_screen.dart
  lib/services/apis/base_api.dart
  lib/services/apis/comment/crud_comment_api.dart
Labels: feature

#102 close #101 show provider in user setting
  lib/models/user/user_model.dart
  lib/screens/user/user_screen.dart
  lib/widgets/cg_popup_menu.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, XS
