Repository CSG6Project1/cambodia_geography_mobile, pull requests merged in 2021-07, with the labels that each got.

#5 add pick place feature
  android/app/src/main/AndroidManifest.xml
  lib/configs/theme_config.dart
  lib/screens/map/map_screen.dart
  lib/widgets/cg_text_field.dart
Labels: feature

#7 6 app localization setup
  l10n.yaml
  lib/app.dart
  lib/exports/exports.dart
  lib/exports/widgets_exports.dart
  lib/l10n/app_en.arb
  lib/l10n/app_km.arb
  lib/main.dart
  lib/screens/home/home_screen.dart
  lib/screens/user/user_screen.dart
  lib/services/storages/locale_storage.dart
  pubspec.lock
  pubspec.yaml
Labels: core, feature

#8 consistent cg widget name
  lib/screens/404/not_found_screen.dart
  lib/screens/admin/admin_screen.dart
  lib/screens/admin/edit_place_screen.dart
  lib/screens/auth/login_screen.dart
  lib/screens/auth/signup_screen.dart
  lib/screens/district/district_screen.dart
  lib/screens/home/home_screen.dart
  lib/screens/map/map_screen.dart
  lib/screens/place_detail/place_detail_screen.dart
  lib/screens/places/places_screen.dart
  lib/screens/search/search_filter_screen.dart
  lib/screens/search/search_screen.dart
  lib/screens/user/bookmark_screen.dart
  lib/screens/user/user_screen.dart
  lib/widgets/cg_app_bar_title.dart
Labels: enhancement

#9 2 home screen design
  lib/constants/config_constant.dart
  lib/helper/number_helper.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/local_widget/province_card.dart
  pubspec.lock
  pubspec.yaml
Labels: design

#14 10 detail district screen
  lib/screens/district/district_screen.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/local_widget/province_card.dart
Labels: design

#17 add province photo
  assets/images/province_images/banteaymeanchey.jpg
  assets/images/province_images/battambong.jpg
  assets/images/province_images/kampongcham.jpg
  assets/images/province_images/kampongchhnang.jpg
  assets/images/province_images/kampongspeu.jpg
  assets/images/province_images/kampongthom.jpg
  assets/images/province_images/kampot.jpg
  assets/images/province_images/kandal.jpg
  assets/images/province_images/kep.jpg
  assets/images/province_images/kohkong.jpg
  assets/images/province_images/kratie.jpg
  assets/images/province_images/mondulkiri.jpg
  assets/images/province_images/oddarmeanchey.jpg
  assets/images/province_images/pailin.jpg
  assets/images/province_images/phnompenh.jpg
  assets/images/province_images/preahsihanouk.jpg
  assets/images/province_images/preahvihear.jpg
  assets/images/province_images/preyveng.jpg
  assets/images/province_images/pursat.jpg
  assets/images/province_images/ratanakkiri.jpg
  assets/images/province_images/siemreap.jpg
  assets/images/province_images/stungtreng.jpg
  assets/images/province_images/svayreang.jpg
  assets/images/province_images/takao.jpg
  assets/images/province_images/tboungkhmum.jpg
  assets/tb_province.json
  lib/models/tb_province_model.dart
  lib/screens/home/local_widget/province_card.dart
  pubspec.yaml
Labels: design

#19 18 home enhancement
  lib/screens/home/home_screen.dart
  lib/screens/home/local_widgets/province_card.dart
  pubspec.lock
Labels: enhancement

#16 close #15 search screen design
  lib/configs/route_config.dart
  lib/screens/home/home_screen.dart
  lib/screens/search/cg_search_delegate.dart
  lib/screens/search/search_screen.dart
  pubspec.lock
Labels: design

#21 20 enhance search home connection
  lib/screens/home/home_screen.dart
  lib/screens/search/cg_search_delegate.dart
  lib/widgets/cg_menu_leading_button.dart
  pubspec.lock
Labels: design, enhancement

#23 22 consistent divider color & app bar
  lib/screens/district/district_screen.dart
  lib/screens/home/local_widgets/province_card.dart
Labels: design

#25 24 setup network & api
  .gitignore
  lib/constants/api_constant.dart.example
  lib/models/apis/object_name_url_model.dart
  lib/services/apis/base_api.dart
  lib/services/apis/base_app_api.dart
  lib/services/apis/base_resource_owner_api.dart
  lib/services/base_storages/secure_preference_storage.dart
  lib/services/networks/app_network.dart
  lib/services/networks/base_network.dart
  lib/services/networks/interceptors/default_interceptor.dart
  lib/services/networks/interceptors/user_token_interceptor.dart
  lib/services/networks/retry_policy/refresh_token_policy.dart
  lib/services/networks/user_token_network.dart
  lib/services/storages/headers_storage.dart
  pubspec.lock
  pubspec.yaml
  test/apis/uri_test.dart
Labels: S, core

#27 26 setup weather api
  android/build.gradle
  lib/configs/route_config.dart
  lib/constants/api_constant.dart.example
  lib/screens/home/local_widgets/province_card.dart
  lib/screens/province/province_detail_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#32 31 update app package name
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/cambodiageography/app/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  pubspec.lock
  pubspec.yaml
Labels: XS, core

#33 30 firebase integration
  .gitignore
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/build.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  ios/build/XCBuildData/36cfaa7087c052f21e3a3ba2cd6b26e9-desc.xcbuild
  ios/build/XCBuildData/36cfaa7087c052f21e3a3ba2cd6b26e9-manifest.xcbuild
  ios/build/XCBuildData/BuildDescriptionCacheIndex-0a404a1e3070501d4981d567f107f41a
  ios/build/XCBuildData/build.db
  ios/build/XCBuildData/cbc9b81430f6ab8ca133a0a91403ec69-desc.xcbuild
  ios/build/XCBuildData/cbc9b81430f6ab8ca133a0a91403ec69-manifest.xcbuild
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: XS, core

#35 34 social auth integration
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  ios/Runner/Info.plist
  lib/screens/user/user_screen.dart
  lib/services/authentications/social_auth_service.dart
  pubspec.lock
  pubspec.yaml
Labels: XS, core

#37 36 app authentication setup
  ios/Podfile.lock
  lib/models/apis/user_token_model.dart
  lib/screens/auth/login_screen.dart
  lib/services/authentications/auth_api.dart
  lib/services/networks/base_network.dart
  lib/services/networks/interceptors/default_interceptor.dart
  lib/services/networks/retry_policy/refresh_token_policy.dart
  lib/services/storages/user_token_storage.dart
Labels: XS, core

#39 close #11 province place
  ios/Flutter/Release.xcconfig
  ios/Runner.xcodeproj/project.pbxproj
  lib/configs/route_config.dart
  lib/models/places/place_model.dart
  lib/screens/home/local_widgets/province_card.dart
  lib/screens/places/places_screen.dart
  pubspec.lock
  test/apis/places/places_api_test.dart
Labels: design, feature

#41 40 handle no image place screen
  assets/images/helper_image/placeholder.png
  lib/models/places/image_model.dart
  lib/models/places/place_model.dart
  lib/screens/home/local_widgets/province_card.dart
  lib/screens/places/places_screen.dart
  lib/widgets/cg_custom_shimmer.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#44 close #43 search filter screen
  lib/screens/search/search_filter_screen.dart
  lib/widgets/cg_app_bar_title.dart
  lib/widgets/cg_dropdown_field.dart
  pubspec.lock
Labels: design

#47 close #12 place detail screen design
  .fvm/flutter_sdk
  ios/Runner.xcodeproj/project.pbxproj
  lib/configs/route_config.dart
  lib/screens/place_detail/local_widgets/place_title.dart
  lib/screens/place_detail/place_detail_screen.dart
  lib/screens/places/local_widgets/place_card.dart
  lib/screens/places/places_screen.dart
  lib/widgets/cg_button.dart
  lib/widgets/cg_image_view.dart
  lib/widgets/cg_on_tap_effect.dart
  pubspec.lock
  pubspec.yaml
Labels: design, feature

#50 update search filter screen
  lib/screens/admin/edit_place_screen.dart
  lib/screens/search/cg_search_delegate.dart
  lib/screens/search/search_filter_screen.dart
Labels: design

#51 close #48 comment place
  .fvm/flutter_sdk
  ios/Runner.xcodeproj/project.pbxproj
  lib/app.dart
  lib/app_builder.dart
  lib/configs/route_config.dart
  lib/helpers/date_helper.dart
  lib/models/comment/comment_list_model.dart
  lib/models/comment/comment_model.dart
  lib/models/places/comment_model.dart
  lib/screens/comment/comment_screen.dart
  lib/screens/place_detail/place_detail_screen.dart
  lib/services/apis/comment/comment_api.dart
  lib/services/local/local_format_service.dart
  pubspec.lock
  pubspec.yaml
Labels: design, feature

#53 close #52 search history
  lib/screens/home/home_screen.dart
  lib/screens/search/cg_search_delegate.dart
  lib/screens/search/search_history_storage.dart
Labels: design, enhancement, feature

#56 55 retry token on send
  lib/services/apis/base_api.dart
  lib/services/networks/base_network.dart
  lib/services/networks/interceptors/user_token_interceptor.dart
  lib/services/networks/retry_policy/refresh_token_policy.dart
  lib/services/networks/user_token_network.dart
Labels: S, core
