Repository CSG6Project1/cambodia_geography_mobile, pull requests merged in 2021-09, with the labels that each got.

#105 close #104 province detail with api
  ios/Podfile.lock
  lib/screens/admin/local_widgets/place_list.dart
  lib/screens/place_detail/local_widgets/place_title.dart
  lib/screens/province/province_detail_screen.dart
  lib/widgets/cg_image_appbar.dart
  lib/widgets/cg_text_shimmer.dart
Labels: design, feature

#108 close #103 place listing on google map
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  ios/Runner/AppDelegate.swift
  lib/helpers/app_helper.dart
  lib/models/places/place_model.dart
  lib/screens/map/local_widgets/carousel_place_list.dart
  lib/screens/map/local_widgets/map_button.dart
  lib/screens/map/local_widgets/place_info_field.dart
  lib/screens/map/map_screen.dart
  lib/screens/place_detail/local_widgets/place_title.dart
  lib/screens/place_detail/place_detail_screen.dart
  lib/screens/province/province_detail_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, S

#110 close #109 carousel place pagination
  lib/models/apis/base_list_model.dart
  lib/models/places/place_model.dart
  lib/screens/map/local_widgets/carousel_place_list.dart
  lib/screens/map/map_screen.dart
  lib/services/apis/places/base_places_api.dart
  lib/services/apis/places/places_api.dart
  lib/services/apis/search/search_api.dart
  lib/services/apis/search/search_filter_api.dart
Labels: enhancement

#113 close #112 improve user screen
  lib/app.dart
  lib/providers/theme_provider.dart
  lib/screens/user/local_widgets/setting_tile.dart
  lib/screens/user/local_widgets/social_tiles.dart
  lib/screens/user/local_widgets/theme_mode_tile.dart
  lib/screens/user/local_widgets/user_infos_tile.dart
  lib/screens/user/local_widgets/user_setting_app_bar.dart
  lib/screens/user/user_screen.dart
  lib/services/apis/users/user_account_linkages_api.dart
Labels: enhancement, XS

#115 close #114 add place type on admin
  lib/constants/app_constant.dart
  lib/screens/admin/local_widgets/place_list.dart
Labels: bug, enhancement

#118 close #117 update search history index
  lib/screens/search/cg_search_delegate.dart
  lib/screens/search/search_filter_screen.dart
Labels: bug

#119 close #116 setup deeplink for email verification
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  ios/build/XCBuildData/0ed93e97391c16db40ab827318e989a7-manifest.xcbuild
  ios/build/XCBuildData/65f81355d186c032425c358d3ef2e74c-manifest.xcbuild
  ios/build/XCBuildData/d47fb4d6231d09cf75dcc7e15de453fb-manifest.xcbuild
  ios/build/XCBuildData/f9f1127994614da54ca554413075c44c-manifest.xcbuild
  pubspec.lock
  pubspec.yaml
Labels: feature, XS

#120 111 place detail report
  ios/Podfile.lock
  lib/screens/comment/comment_screen.dart
  lib/screens/place_detail/place_detail_screen.dart
  lib/screens/province/province_detail_screen.dart
  lib/widgets/cg_image_appbar.dart
Labels: bug, enhancement

#123 close #122 update search filter API
  lib/screens/search/cg_search_delegate.dart
  lib/screens/search/search_filter_screen.dart
  lib/services/apis/search/search_api.dart
Labels: enhancement, S

#125 124 update comment on upload
  lib/screens/comment/comment_screen.dart
  lib/screens/province/province_detail_screen.dart
Labels: enhancement, design

#127 close #126 remove bookmark
  lib/models/places/bookmark_model.dart
  lib/models/places/place_model.dart
  lib/screens/place_detail/place_detail_screen.dart
  lib/screens/user/bookmark_screen.dart
  lib/services/apis/base_api.dart
  lib/services/apis/bookmarks/bookmark_api.dart
  lib/services/apis/bookmarks/bookmark_remove_all_places_api.dart
  lib/services/apis/bookmarks/bookmark_remove_multiple_places_api.dart
  lib/services/apis/bookmarks/bookmark_remove_place_api.dart
Labels: feature

#128 close #107 pick place google map + autocompletion
  lib/screens/map/map_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, XS

#130 close #129 bookmark enhancement
  lib/screens/place_detail/place_detail_screen.dart
  lib/screens/user/bookmark_screen.dart
  lib/services/apis/bookmarks/bookmark_api.dart
Labels: enhancement

#136 133 enhance padding in comment
  ios/Podfile.lock
  lib/screens/comment/comment_screen.dart
  lib/widgets/cg_bottom_nav_wrapper.dart
Labels: design

#137 close #134 change app icon
  android/app/src/main/res/ic_launcher-web.png
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/playstore-icon.png
  android/app/src/main/res/values/ic_launcher_background.xml
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/iTunesArtwork@1x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/iTunesArtwork@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/iTunesArtwork@3x.png
Labels: core, XS

#138 close #135 add localization translation
  assets/translations/en.json
  assets/translations/km.json
  ios/Runner/Info.plist
  lib/app.dart
  lib/main.dart
  lib/screens/search/cg_search_delegate.dart
  lib/screens/user/bookmark_screen.dart
  lib/screens/user/user_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: core

#145 close #144 update homepage add search field
  lib/screens/admin/local_widgets/place_list.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/local_widgets/search_button.dart
  lib/widgets/text_fields/cg_text_field.dart
Labels: bug, enhancement, design, S

#149 close #148 improve about us screen
  android/app/build.gradle
  lib/configs/route_config.dart
  lib/models/info/member_model.dart
  lib/screens/drawer/about_us_screen.dart
  lib/screens/drawer/app_drawer.dart
  lib/screens/places/local_widgets/place_card.dart
  lib/services/apis/info/member_api.dart
  lib/utils/translation_utils.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, design

#152 close #151 remove member page & add help screen
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/configs/route_config.dart
  lib/screens/drawer/about_us_screen.dart
  lib/screens/drawer/app_drawer.dart
  lib/screens/drawer/help_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, design, S

#154 fix: app review bugs fix and improvement
  ios/Podfile.lock
  lib/configs/route_config.dart
  lib/screens/drawer/app_drawer.dart
  lib/screens/drawer/help_screen.dart
  lib/screens/map/map_screen.dart
  lib/screens/user/user_screen.dart
Labels: bug, XS

#155 fix: various bugs fix
  android/app/src/main/AndroidManifest.xml
  lib/configs/cg_page_route.dart
  lib/configs/route_config.dart
  lib/screens/admin/local_widgets/place_list.dart
  lib/screens/auth/login_screen.dart
  lib/screens/auth/signup_screen.dart
  lib/screens/drawer/app_drawer.dart
  lib/screens/drawer/help_screen.dart
  lib/screens/map/local_widgets/carousel_place_list.dart
  lib/screens/map/map_screen.dart
  lib/screens/province/province_detail_screen.dart
  lib/screens/user/bookmark_screen.dart
  lib/screens/user/local_widgets/social_tiles.dart
  lib/screens/user/user_screen.dart
  lib/splash_screen.dart
  lib/widgets/cg_bottom_nav_wrapper.dart
  lib/widgets/cg_popup_menu.dart
Labels: bug, XS

#157 close #156 remember search filter
  lib/configs/route_config.dart
  lib/screens/admin/edit_place_screen.dart
  lib/screens/map/local_widgets/place_info_field.dart
  lib/screens/place_detail/place_detail_screen.dart
  lib/screens/search/cg_search_delegate.dart
  lib/screens/search/search_filter_screen.dart
  lib/widgets/cg_dropdown_field.dart
Labels: enhancement

#159 close #158 home screen translation
  assets/translations/en.json
  assets/translations/km.json
  lib/app.dart
  lib/main.dart
  lib/models/base_model.dart
  lib/providers/theme_provider.dart
  lib/providers/user_provider.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/local_widgets/province_card.dart
  lib/splash_screen.dart
  lib/utils/initialize_utils.dart
  lib/utils/translation_utils.dart
Labels: design, XS

#161 close #160 disctrict screen translation
  assets/translations/en.json
  assets/translations/km.json
  lib/screens/district/district_screen.dart
  lib/screens/home/local_widgets/province_card.dart
Labels: design, XS

#163 close #162 drawer & user screen translation
  assets/translations/en.json
  assets/translations/km.json
  lib/screens/drawer/app_drawer.dart
  lib/screens/home/local_widgets/verify_email_banner.dart
  lib/screens/user/local_widgets/social_tiles.dart
  lib/screens/user/local_widgets/theme_mode_tile.dart
  lib/screens/user/local_widgets/user_infos_tile.dart
  lib/screens/user/local_widgets/user_setting_app_bar.dart
  lib/screens/user/user_screen.dart
Labels: design, XS

#167 close #166 place detail & comment translation
  assets/translations/en.json
  assets/translations/km.json
  lib/main.dart
  lib/screens/admin/local_widgets/place_list.dart
  lib/screens/comment/comment_screen.dart
  lib/screens/map/map_screen.dart
  lib/screens/place_detail/local_widgets/place_title.dart
  lib/screens/place_detail/place_detail_screen.dart
  lib/screens/places/local_widgets/place_card.dart
  lib/screens/places/places_screen.dart
  lib/screens/province/province_detail_screen.dart
  lib/widgets/cg_images_viewer.dart
  lib/widgets/cg_no_data_wrapper.dart
  pubspec.lock
  pubspec.yaml
Labels: design, XS

#170 164 search flow translation
  lib/main.dart
  lib/screens/search/cg_search_delegate.dart
  lib/screens/search/search_filter_screen.dart
  lib/widgets/cg_filter_geo_fields.dart
Labels: design

#171 close #147 add missing translation
  assets/translations/en.json
  assets/translations/km.json
  lib/configs/theme_config.dart
  lib/helpers/app_helper.dart
  lib/screens/404/not_found_screen.dart
  lib/screens/admin/admin_screen.dart
  lib/screens/admin/body_editor_screen.dart
  lib/screens/admin/edit_place_screen.dart
  lib/screens/admin/local_widgets/place_list.dart
  lib/screens/auth/confirmation_screen.dart
  lib/screens/comment/comment_screen.dart
  lib/screens/drawer/app_drawer.dart
  lib/screens/drawer/help_screen.dart
  lib/screens/home/local_widgets/province_card.dart
  lib/screens/province/province_detail_screen.dart
  lib/screens/user/bookmark_screen.dart
  lib/services/apis/base_api.dart
  lib/widgets/cg_button.dart
  lib/widgets/cg_filter_geo_fields.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, XS

#173 close #172 add reference page
  assets/translations/en.json
  assets/translations/km.json
  lib/configs/route_config.dart
  lib/extensions/string_extensions.dart
  lib/helpers/app_helper.dart
  lib/main.dart
  lib/screens/comment/comment_screen.dart
  lib/screens/district/district_screen.dart
  lib/screens/district/reference_screen.dart
  lib/screens/home/local_widgets/province_card.dart
  pubspec.lock
  pubspec.yaml
Labels: design

#184 close #178 fix filter place type not remember
  lib/screens/admin/edit_place_screen.dart
  lib/widgets/cg_filter_geo_fields.dart
Labels: enhancement
